version: 2
jobs:
  test_snap_release:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          command: |
            sudo apt update && sudo apt install -y snapd
            docker run -v $(pwd):$(pwd) -t ubuntu:xenial sh -c "apt update -qq && apt install snapcraft -y && cd $(pwd) && snapcraft && tfswitch --version"
            tfswitch --version
            tfswitch -b ~/.bin --latest

#             sudo snap install tfswitch

workflows:
  version: 2

  build_and_test:
    jobs:
      - test_snap_release

