version: 2
jobs:
  test_snap_build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          command: |
            sudo apt update && sudo apt install -y snapd snapcraft git
            snapcraft
            tfswitch --version
            tfswitch -b ~/.bin --latest


workflows:
  version: 2

  build_and_test:
    jobs:
      - test_snap_build

