version: 2
jobs:
  test_snap_release:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - run:
          command: | 
            sudo snap install tfswitch
            tfswitch --version
            tfswitch -b ~/.bin --latest

workflows:
  version: 2

  build_and_test:
    jobs:
      - test_snap_release

