version: 2
jobs:
  test_snap_build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          command: |
            echo "Installing snapd, git..."
            sudo apt update && sudo apt install -y snapd git
            echo "Installing snapcraft..."
            sudo apt install snapcraft
            echo "Building and installing tfswitch..."
            echo y | snapcraft
            tfswitch --version
            tfswitch -b ~/.bin --latest


workflows:
  version: 2

  build_and_test:
    jobs:
      - test_snap_build

